# Generated by Django 4.1 on 2023-01-04 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario", models.CharField(max_length=250)),
                ("correo", models.CharField(max_length=250)),
                ("contraseña", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Trabajadores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombres", models.CharField(max_length=250)),
                ("apellidos", models.CharField(max_length=250)),
                ("posicion", models.CharField(max_length=250)),
                (
                    "usuario_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dataApi.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tareas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=250)),
                ("descripcion", models.CharField(max_length=250)),
                ("fecha_entrega", models.CharField(max_length=250)),
                ("finalizado", models.BooleanField()),
                (
                    "usuario_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dataApi.user"
                    ),
                ),
            ],
        ),
    ]
