# Generated by Django 4.1 on 2023-01-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dataApi", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="tareas", name="finalizado",),
    ]
